// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: pb/crime.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCrimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCrimeRequest) Reset() {
	*x = GetCrimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_crime_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCrimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCrimeRequest) ProtoMessage() {}

func (x *GetCrimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_crime_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCrimeRequest.ProtoReflect.Descriptor instead.
func (*GetCrimeRequest) Descriptor() ([]byte, []int) {
	return file_pb_crime_proto_rawDescGZIP(), []int{0}
}

type GetCrimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Crimes []*Crime `protobuf:"bytes,1,rep,name=crimes,proto3" json:"crimes,omitempty"`
}

func (x *GetCrimeResponse) Reset() {
	*x = GetCrimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_crime_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCrimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCrimeResponse) ProtoMessage() {}

func (x *GetCrimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_crime_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCrimeResponse.ProtoReflect.Descriptor instead.
func (*GetCrimeResponse) Descriptor() ([]byte, []int) {
	return file_pb_crime_proto_rawDescGZIP(), []int{1}
}

func (x *GetCrimeResponse) GetCrimes() []*Crime {
	if x != nil {
		return x.Crimes
	}
	return nil
}

type Crime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LocationName string  `protobuf:"bytes,2,opt,name=location_name,json=locationName,proto3" json:"location_name,omitempty"`
	Longitude    float64 `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude     float64 `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Description  string  `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Image        string  `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Date         string  `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *Crime) Reset() {
	*x = Crime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_crime_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Crime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Crime) ProtoMessage() {}

func (x *Crime) ProtoReflect() protoreflect.Message {
	mi := &file_pb_crime_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Crime.ProtoReflect.Descriptor instead.
func (*Crime) Descriptor() ([]byte, []int) {
	return file_pb_crime_proto_rawDescGZIP(), []int{2}
}

func (x *Crime) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Crime) GetLocationName() string {
	if x != nil {
		return x.LocationName
	}
	return ""
}

func (x *Crime) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Crime) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Crime) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Crime) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Crime) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

var File_pb_crime_proto protoreflect.FileDescriptor

var file_pb_crime_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x62, 0x2f, 0x63, 0x72, 0x69, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x72, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x32, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x72, 0x69, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x06, 0x63, 0x72, 0x69, 0x6d, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x43, 0x72, 0x69, 0x6d, 0x65, 0x52,
	0x06, 0x63, 0x72, 0x69, 0x6d, 0x65, 0x73, 0x22, 0xc2, 0x01, 0x0a, 0x05, 0x43, 0x72, 0x69, 0x6d,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x32, 0x42, 0x0a, 0x0c,
	0x43, 0x72, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x09,
	0x47, 0x65, 0x74, 0x43, 0x72, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x10, 0x2e, 0x47, 0x65, 0x74, 0x43,
	0x72, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x72, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67,
	0x6f, 0x73, 0x70, 0x6f, 0x64, 0x69, 0x6e, 0x7a, 0x65, 0x72, 0x6b, 0x61, 0x6c, 0x6f, 0x2f, 0x63,
	0x72, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_crime_proto_rawDescOnce sync.Once
	file_pb_crime_proto_rawDescData = file_pb_crime_proto_rawDesc
)

func file_pb_crime_proto_rawDescGZIP() []byte {
	file_pb_crime_proto_rawDescOnce.Do(func() {
		file_pb_crime_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_crime_proto_rawDescData)
	})
	return file_pb_crime_proto_rawDescData
}

var file_pb_crime_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_crime_proto_goTypes = []interface{}{
	(*GetCrimeRequest)(nil),  // 0: GetCrimeRequest
	(*GetCrimeResponse)(nil), // 1: GetCrimeResponse
	(*Crime)(nil),            // 2: Crime
}
var file_pb_crime_proto_depIdxs = []int32{
	2, // 0: GetCrimeResponse.crimes:type_name -> Crime
	0, // 1: CrimeService.GetCrimes:input_type -> GetCrimeRequest
	1, // 2: CrimeService.GetCrimes:output_type -> GetCrimeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_crime_proto_init() }
func file_pb_crime_proto_init() {
	if File_pb_crime_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_crime_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCrimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_crime_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCrimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_crime_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Crime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_crime_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_crime_proto_goTypes,
		DependencyIndexes: file_pb_crime_proto_depIdxs,
		MessageInfos:      file_pb_crime_proto_msgTypes,
	}.Build()
	File_pb_crime_proto = out.File
	file_pb_crime_proto_rawDesc = nil
	file_pb_crime_proto_goTypes = nil
	file_pb_crime_proto_depIdxs = nil
}
